setwd("C:/Users/Gabriel Yedid/Desktop/YGD_MESAPROJECT/NEWOUTPUTFILES/")

SEED_LIST_ALL = read.table("MESA_seed_list.txt",header=F)
EXTTIME = 300
ENDSIMTIME = 600

OUTMAT = matrix(data=0.00, nrow=dim(SEED_LIST_ALL)[1], ncol=3)
colnames(OUTMAT) = c("SEED","POSTEXT_PEAKIMBAL_TIME","POSTEXT_PEAKIMBAL_VAL")

for (s in 1:dim(SEED_LIST_ALL)[1]) {
  SEEDVAL = as.character(SEED_LIST_ALL[s,1])
  message(SEEDVAL)
  INFILENAME = paste("MESA_X5Balance_test_s",SEEDVAL,"_lotrtext0.9_NEW.out",sep="")
  
  DATA = read.table(INFILENAME,header=T)
  
  EXTTIMEROW = which(DATA[,1]==EXTTIME)
  
  POSTEXT_DATA = DATA[(EXTTIMEROW+1):dim(DATA)[1],]
  
  POSTEXT_PEAKIMBAL_VAL = max(POSTEXT_DATA[,6])
  POSTEXT_PEAKIMBAL_ROW = which(POSTEXT_DATA[,6] == max(POSTEXT_DATA[,6]))
  POSTEXT_PEAKIMBAL_TIME = POSTEXT_DATA[POSTEXT_PEAKIMBAL_ROW,1] 
  
  if(POSTEXT_PEAKIMBAL_TIME == ENDSIMTIME) {
    POSTEXT_PEAKIMBAL_ROW = POSTEXT_PEAKIMBAL_ROW-1
    POSTEXT_PEAKIMBAL_TIME = POSTEXT_DATA[POSTEXT_PEAKIMBAL_ROW,1]
  }
  
  #SEED POSTEXT_PEAKIMBAL_TIME POSTEXT_PEAKIMBAL_VAL 
  
  OUTMAT[s,1] = as.numeric(SEEDVAL)
  OUTMAT[s,2] = POSTEXT_PEAKIMBAL_TIME
  OUTMAT[s,3] = POSTEXT_PEAKIMBAL_VAL
}



