---
title: "2way Anova"
author: "irene"
date: "2/11/2017"
output: word_document
---

```{r}
CSR_DATA = read.table("CSR_2.txt", header=T,sep="\t")
attach(CSR_DATA) #NB not provided by the authors and it does not seem to be used for any test.

DATA2 = read.table("ENDSIM3.txt", header=T,sep="\t")
attach(DATA2) #provided but not used

DATA3 = read.table("ENDSIM4.txt", header=T,sep="\t")
attach(DATA3)#not provided

PEAK_IMBAL = read.table("PEAKIMBAL.txt", header=T,sep="\t")
attach(PEAK_IMBAL) #not provided

CSR_END_MID = read.table("CSR_END_MID_2FACT.txt", header=T,sep="\t")
attach(CSR_END_MID)#they used a new file which Gabe sent us by email


PEAK_IMBAL = read.table("PEAKIMBAL_2FACT_REDO.txt", header=T,sep="\t")
attach(PEAK_IMBAL) #provided but not used
```


```{r} 
# I added this part because I thought it could be interesting to look at any significant treatment-intensity interactions for CSR, post CSR interval times and end simulation time, as they show in the results.  
CSR <- read.table("CSR_anova.txt", header=T,sep="\t")
colnames(CSR) = c("TREAT","INTENSITY","COLBLUM")
attach(CSR)
tapply(COLBLUM,TREAT,mean)
tapply(COLBLUM,INTENSITY,mean)
tapply(COLBLUM,TREAT:INTENSITY,mean)

with_int <- aov(COLBLUM ~ TREAT*INTENSITY)
summary(with_int)
summary.lm(with_int)

no_int = aov(COLBLUM ~ TREAT+INTENSITY)
summary(no_int)
summary.lm(no_int)

anova(no_int,with_int)
TukeyHSD(with_int)
plot(TukeyHSD(with_int))

TukeyHSD(no_int)
plot(TukeyHSD(no_int))


boxplot(COLBLUM~TREAT, notch=T)
boxplot(COLBLUM~INTENSITY, notch=T)

interaction.plot(TREAT,INTENSITY,COLBLUM,type="b")

INT2 = factor(INTENSITY)
levels(INT2)
levels(INT2)[3]="highest"
levels(INT2)[c(1,2)]="lowest"
no_int2 = aov(COLBLUM~TREAT+INT2)
summary(no_int2)
anova(no_int,no_int2)
```


```{r pressure, echo=FALSE}
CSR_END_1Q = read.table("CSR_ENDMID_1Q.txt", header=T,sep="\t")
CSR_END_3Q = read.table("CSR_ENDMID_3Q.txt", header=T,sep="\t")
CSR_END_MIDNEW = read.table("CSR_ENDMID_NEW2017.txt", header=T,sep="\t")

colnames(CSR_END_1Q) = c("TREAT","INTENSITY","COLBLUM")
attach(CSR_END_1Q)

tapply(COLBLUM,TREAT,mean)
tapply(COLBLUM,INTENSITY,mean)
tapply(COLBLUM,TREAT:INTENSITY,mean)

with_int <- aov(COLBLUM ~ TREAT*INTENSITY)
summary(with_int)
summary.lm(with_int)

no_int = aov(COLBLUM ~ TREAT+INTENSITY)
summary(no_int)
summary.lm(no_int)

anova(no_int,with_int)

TukeyHSD(with_int)
plot(TukeyHSD(with_int))

TukeyHSD(no_int)
plot(TukeyHSD(no_int))


boxplot(COLBLUM~TREAT, notch=T)
boxplot(COLBLUM~INTENSITY, notch=T)

interaction.plot(TREAT,INTENSITY,COLBLUM,type="b")

INT2 = factor(INTENSITY)
levels(INT2)
levels(INT2)[3]="highest"
levels(INT2)[c(1,2)]="lowest"
no_int2 = aov(COLBLUM~TREAT+INT2)
summary(no_int2)
anova(no_int,no_int2)
```

```{r}
CSR_END_3Q = read.table("CSR_ENDMID_3Q.txt", header=T,sep="\t")colnames(CSR_END_3Q) = c("TREAT","INTENSITY","COLBLUM")
attach(CSR_END_1Q)

tapply(COLBLUM,TREAT,mean)
tapply(COLBLUM,INTENSITY,mean)
tapply(COLBLUM,TREAT:INTENSITY,mean)

with_int <- aov(COLBLUM ~ TREAT*INTENSITY)
summary(with_int)
summary.lm(with_int)

no_int = aov(COLBLUM ~ TREAT+INTENSITY)
summary(no_int)
summary.lm(no_int)

anova(no_int,with_int)

TukeyHSD(with_int)
plot(TukeyHSD(with_int))

TukeyHSD(no_int)
plot(TukeyHSD(no_int))


boxplot(COLBLUM~TREAT, notch=T)
boxplot(COLBLUM~INTENSITY, notch=T)

interaction.plot(TREAT,INTENSITY,COLBLUM,type="b")

INT2 = factor(INTENSITY)
levels(INT2)
levels(INT2)[3]="highest"
levels(INT2)[c(1,2)]="lowest"
no_int2 = aov(COLBLUM~TREAT+INT2)
summary(no_int2)
anova(no_int,no_int2)
```

```{r}
CSR_END_MIDNEW = read.table("CSR_ENDMID_NEW2017.txt", header=T,sep="\t")
colnames(CSR_END_MIDNEW) = c("TREAT","INTENSITY","COLBLUM")
attach(CSR_END_MIDNEW)
tapply(COLBLUM,TREAT,mean)
tapply(COLBLUM,INTENSITY,mean)
tapply(COLBLUM,TREAT:INTENSITY,mean)

with_int <- aov(COLBLUM ~ TREAT*INTENSITY)
summary(with_int)
summary.lm(with_int)

no_int = aov(COLBLUM ~ TREAT+INTENSITY)
summary(no_int)
summary.lm(no_int)

anova(no_int,with_int)
TukeyHSD(with_int)
plot(TukeyHSD(with_int))

TukeyHSD(no_int)
plot(TukeyHSD(no_int))


boxplot(COLBLUM~TREAT, notch=T)
boxplot(COLBLUM~INTENSITY, notch=T)

interaction.plot(TREAT,INTENSITY,COLBLUM,type="b")

INT2 = factor(INTENSITY)
levels(INT2)
levels(INT2)[3]="highest"
levels(INT2)[c(1,2)]="lowest"
no_int2 = aov(COLBLUM~TREAT+INT2)
summary(no_int2)
anova(no_int,no_int2)
```

```{r}
ENDSIM <- read.table("ENDSIM_anova.txt", header=T,sep="\t")
colnames(ENDSIM) = c("TREAT","INTENSITY","COLBLUM")
attach(ENDSIM)
tapply(COLBLUM,TREAT,mean)
tapply(COLBLUM,INTENSITY,mean)
tapply(COLBLUM,TREAT:INTENSITY,mean)

with_int <- aov(COLBLUM ~ TREAT*INTENSITY)
summary(with_int)
summary.lm(with_int)

no_int = aov(COLBLUM ~ TREAT+INTENSITY)
summary(no_int)
summary.lm(no_int)

anova(no_int,with_int)
TukeyHSD(with_int)
plot(TukeyHSD(with_int))

TukeyHSD(no_int)
plot(TukeyHSD(no_int))


boxplot(COLBLUM~TREAT, notch=T)
boxplot(COLBLUM~INTENSITY, notch=T)

interaction.plot(TREAT,INTENSITY,COLBLUM,type="b")

INT2 = factor(INTENSITY)
levels(INT2)
levels(INT2)[3]="highest"
levels(INT2)[c(1,2)]="lowest"
no_int2 = aov(COLBLUM~TREAT+INT2)
summary(no_int2)
anova(no_int,no_int2)

```

