---
title: "dunnett tests"
author: "irene"
date: "26/10/2017"
output: word_document
---
Dunnett's test for comparison against a standard--CTRL vs. all other treatments
```{r}
#set the working directory
library(multcomp)
ENDSIM_1FACT = read.table("END_SIM1FACT.txt",header=F,sep="\t")
colnames(ENDSIM_1FACT) = c("TREAT_INTENS","VALUE")
attach(ENDSIM_1FACT)
ANVA = aov(VALUE~TREAT_INTENS,ENDSIM_1FACT)
ANVA
summary.aov(ANVA)

```

```{r}
MULTCOMP = glht(ANVA, linfct=mcp(TREAT_INTENS = "Dunnett"))
summary(MULTCOMP)

MULTCOMP = glht(ANVA, linfct=mcp(TREAT_INTENS = "Dunnett"))

summary(MULTCOMP)
aov(formula = VALUE ~ TREAT_INTENS, data = ENDSIM_1FACT)
detach(ENDSIM_1FACT)
```

```{r}
PEAKIMBAL_1FACT = read.table("PEAKIMBAL_1FACT.txt",header=F,sep="\t")
colnames(PEAKIMBAL_1FACT) = c("TREAT_INTENS","VALUE")
attach(PEAKIMBAL_1FACT)
ANVA = aov(VALUE~TREAT_INTENS,PEAKIMBAL_1FACT)
summary.aov(ANVA)
#performing a Dunnett'test 
MULTCOMP = glht(ANVA, linfct=mcp(TREAT_INTENS = "Dunnett"))
summary(MULTCOMP)

summary(MULTCOMP)
```

```{r}
PEAKIMBAL_1FACT = read.table("PEAKIMBAL_1FACT_REDO.txt",header=T,sep="\t")
colnames(PEAKIMBAL_1FACT) = c("TREAT_INTENS","VALUE")
attach(PEAKIMBAL_1FACT)
ANVA = aov(VALUE~TREAT_INTENS,PEAKIMBAL_1FACT)
summary.aov(ANVA)
```

```{r}
MULTCOMP = glht(ANVA, linfct=mcp(TREAT_INTENS = "Dunnett"))
summary(MULTCOMP)
```

```{r}
CSR_VS_PREEXT_1FACT = read.table("CSR_VS_PREEXT_1FACT.txt",header=F,sep="\t")

colnames(CSR_VS_PREEXT_1FACT) = c("TREAT_INTENS","VALUE")
attach(CSR_VS_PREEXT_1FACT)
ANVA = aov(VALUE~TREAT_INTENS,CSR_VS_PREEXT_1FACT)
summary.aov(ANVA)
```

```{r}
MULTCOMP = glht(ANVA, linfct=mcp(TREAT_INTENS = "Dunnett"))
summary(MULTCOMP)
```

