---
title: "Collect Key CSR Root Age Times"
author: "irene"
date: "23/10/2017"
output: word_document
---

```{r}
SEED_LIST_ALL = read.table("MESA_seed_list.txt",header=F)

NCOLS = 7
ROOT_TIME_MAT = matrix(data=0,nrow = dim(SEED_LIST_ALL)[1],ncol=NCOLS)
ROOT_TIME_MAT[,1] = SEED_LIST_ALL[,1]
colnames(ROOT_TIME_MAT) = c("SEED","PRE-EXT","POST-EVENT","CSR","PEAK IMBAL", "CSR-END MID","END SIM")

PRE_EXT_TIME = 300
POST_EVENT_TIME = 305
CTRL_CSR_GRAND_MEAN_TIME = 345
END_SIM_TIME = 600
CSR_END_MID_TIME = 475

for (s in 1:dim(SEED_LIST_ALL)[1]) {
  SEEDVAL = as.character(SEED_LIST_ALL[s,1])
  message(SEEDVAL)
  INFILENAME = paste("MESA_X5Balance_test_s",SEEDVAL,"_noext0.9_NEW.out",sep="")
  
  DATA = read.table(INFILENAME,header=T)
  
  PRE_EXT_TIME_ROW = which(DATA[,1]==PRE_EXT_TIME)
  PRE_EXT_TIME_RTDIST = DATA[PRE_EXT_TIME_ROW,12]
  PRE_EXT_TIME_ROOTAGE = PRE_EXT_TIME - PRE_EXT_TIME_RTDIST
  
  POST_EVENT_TIME_ROW = which(DATA[,1]==POST_EVENT_TIME)
  POST_EVENT_TIME_RTDIST = DATA[POST_EVENT_TIME_ROW,12]
  POST_EVENT_TIME_ROOTAGE = POST_EVENT_TIME - POST_EVENT_TIME_RTDIST
  
  CCGM_TIME_ROW = which(DATA[,1]==CTRL_CSR_GRAND_MEAN_TIME)
  CCGM_TIME_RTDIST = DATA[CCGM_TIME_ROW,12]
  CCGM_TIME_ROOTAGE = CTRL_CSR_GRAND_MEAN_TIME - CCGM_TIME_RTDIST
  
  PEAK_IMBAL_VAL = max(DATA[,6])
  PEAK_IMBAL_ROW = which(DATA[,6]==PEAK_IMBAL_VAL)
  PEAK_IMBAL_TIME = DATA[PEAK_IMBAL_ROW,1]
  PEAK_IMBAL_RTDIST = DATA[PEAK_IMBAL_ROW,12]
  PEAK_IMBAL_ROOTAGE = PEAK_IMBAL_TIME - PEAK_IMBAL_RTDIST
  
  CSR_END_MID_TIME_ROW = which(DATA[,1]==CSR_END_MID_TIME)
  CSR_END_MID_TIME_RTDIST = DATA[CSR_END_MID_TIME_ROW,12]
  CSR_END_MID_ROOTAGE = CSR_END_MID_TIME - CSR_END_MID_TIME_RTDIST
  
  END_SIM_TIME_ROW = which(DATA[,1]==END_SIM_TIME)
  END_SIM_TIME_RTDIST = DATA[END_SIM_TIME_ROW,12]
  END_SIM_TIME_ROOTAGE = END_SIM_TIME - END_SIM_TIME_RTDIST
  
  ROOT_TIME_MAT[s,2] = PRE_EXT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,3] = POST_EVENT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,4] = CCGM_TIME_ROOTAGE
  ROOT_TIME_MAT[s,5] = PEAK_IMBAL_ROOTAGE
  ROOT_TIME_MAT[s,6] = CSR_END_MID_ROOTAGE
  ROOT_TIME_MAT[s,7] = END_SIM_TIME_ROOTAGE

}

write.table(ROOT_TIME_MAT,"CTRL_KeyRootAgeTimes.out", sep = " ")

```

```{r}
CSR_TIMES = read.table("CSR_times.txt", header=T, sep="\t")

RAND_0.5_CSRTIMES = CSR_TIMES[,2]
HITRT_0.5_CSRTIMES = CSR_TIMES[,3]
LOTRT_0.5_CSRTIMES = CSR_TIMES[,4]

for (s in 1:dim(SEED_LIST_ALL)[1]) {
  SEEDVAL = as.character(SEED_LIST_ALL[s,1])
  message(SEEDVAL)
  INFILENAME = paste("MESA_X5Balance_test_s",SEEDVAL,"_randext0.5_NEW.out",sep="")
  
  DATA = read.table(INFILENAME,header=T)
  
  PRE_EXT_TIME_ROW = which(DATA[,1]==PRE_EXT_TIME)
  PRE_EXT_TIME_RTDIST = DATA[PRE_EXT_TIME_ROW,12]
  PRE_EXT_TIME_ROOTAGE = PRE_EXT_TIME - PRE_EXT_TIME_RTDIST
  
  POST_EVENT_TIME_ROW = which(DATA[,1]==POST_EVENT_TIME)
  POST_EVENT_TIME_RTDIST = DATA[POST_EVENT_TIME_ROW,12]
  POST_EVENT_TIME_ROOTAGE = POST_EVENT_TIME - POST_EVENT_TIME_RTDIST
  
  RAND_CSR_TIME = RAND_0.5_CSRTIMES[s]
  
  RCT_TIME_ROW = which(DATA[,1]==RAND_CSR_TIME)
  RCT_TIME_RTDIST = DATA[RCT_TIME_ROW,12]
  RCT_TIME_ROOTAGE = RAND_CSR_TIME - RCT_TIME_RTDIST
  
  PEAK_IMBAL_VAL = max(DATA[,6])
  PEAK_IMBAL_ROW = which(DATA[,6]==PEAK_IMBAL_VAL)
  PEAK_IMBAL_TIME = DATA[PEAK_IMBAL_ROW,1]
  PEAK_IMBAL_RTDIST = DATA[PEAK_IMBAL_ROW,12]
  PEAK_IMBAL_ROOTAGE = PEAK_IMBAL_TIME - PEAK_IMBAL_RTDIST
  
  CSR_END_MID_TIME = ((END_SIM_TIME - RAND_CSR_TIME)%/%2) + RAND_CSR_TIME
  if ((CSR_END_MID_TIME %% 5) > 0) CSR_END_MID_TIME = CSR_END_MID_TIME + 3 
  
  CSR_END_MID_TIME_ROW = which(DATA[,1]==CSR_END_MID_TIME)
  CSR_END_MID_TIME_RTDIST = DATA[CSR_END_MID_TIME_ROW,12]
  CSR_END_MID_ROOTAGE = CSR_END_MID_TIME - CSR_END_MID_TIME_RTDIST
  
  END_SIM_TIME_ROW = which(DATA[,1]==END_SIM_TIME)
  END_SIM_TIME_RTDIST = DATA[END_SIM_TIME_ROW,12]
  END_SIM_TIME_ROOTAGE = END_SIM_TIME - END_SIM_TIME_RTDIST
  
  ROOT_TIME_MAT[s,2] = PRE_EXT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,3] = POST_EVENT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,4] = RCT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,5] = PEAK_IMBAL_ROOTAGE
  ROOT_TIME_MAT[s,6] = CSR_END_MID_ROOTAGE
  ROOT_TIME_MAT[s,7] = END_SIM_TIME_ROOTAGE
  
}

write.table(ROOT_TIME_MAT,"RAND0.5_KeyRootAgeTimes.out", sep = " ")

```

```{r}
for (s in 1:dim(SEED_LIST_ALL)[1]) {
  SEEDVAL = as.character(SEED_LIST_ALL[s,1])
  message(SEEDVAL)
  INFILENAME = paste("MESA_X5Balance_test_s",SEEDVAL,"_lotrtext0.5_NEW.out",sep="")
  
  DATA = read.table(INFILENAME,header=T)
  
  PRE_EXT_TIME_ROW = which(DATA[,1]==PRE_EXT_TIME)
  PRE_EXT_TIME_RTDIST = DATA[PRE_EXT_TIME_ROW,12]
  PRE_EXT_TIME_ROOTAGE = PRE_EXT_TIME - PRE_EXT_TIME_RTDIST
  
  POST_EVENT_TIME_ROW = which(DATA[,1]==POST_EVENT_TIME)
  POST_EVENT_TIME_RTDIST = DATA[POST_EVENT_TIME_ROW,12]
  POST_EVENT_TIME_ROOTAGE = POST_EVENT_TIME - POST_EVENT_TIME_RTDIST
  
  LOTRT_CSR_TIME = LOTRT_0.5_CSRTIMES[s]
  
  RCT_TIME_ROW = which(DATA[,1]==LOTRT_CSR_TIME)
  RCT_TIME_RTDIST = DATA[RCT_TIME_ROW,12]
  RCT_TIME_ROOTAGE = LOTRT_CSR_TIME - RCT_TIME_RTDIST
  
  PEAK_IMBAL_VAL = max(DATA[,6])
  PEAK_IMBAL_ROW = which(DATA[,6]==PEAK_IMBAL_VAL)
  PEAK_IMBAL_TIME = DATA[PEAK_IMBAL_ROW,1]
  PEAK_IMBAL_RTDIST = DATA[PEAK_IMBAL_ROW,12]
  PEAK_IMBAL_ROOTAGE = PEAK_IMBAL_TIME - PEAK_IMBAL_RTDIST
  
  CSR_END_MID_TIME = ((END_SIM_TIME - RAND_CSR_TIME)%/%2) + RAND_CSR_TIME
  if ((CSR_END_MID_TIME %% 5) > 0) CSR_END_MID_TIME = CSR_END_MID_TIME + 3 
  
  CSR_END_MID_TIME_ROW = which(DATA[,1]==CSR_END_MID_TIME)
  CSR_END_MID_TIME_RTDIST = DATA[CSR_END_MID_TIME_ROW,12]
  CSR_END_MID_ROOTAGE = CSR_END_MID_TIME - CSR_END_MID_TIME_RTDIST
  
  END_SIM_TIME_ROW = which(DATA[,1]==END_SIM_TIME)
  END_SIM_TIME_RTDIST = DATA[END_SIM_TIME_ROW,12]
  END_SIM_TIME_ROOTAGE = END_SIM_TIME - END_SIM_TIME_RTDIST
  
  ROOT_TIME_MAT[s,2] = PRE_EXT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,3] = POST_EVENT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,4] = RCT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,5] = PEAK_IMBAL_ROOTAGE
  ROOT_TIME_MAT[s,6] = CSR_END_MID_ROOTAGE
  ROOT_TIME_MAT[s,7] = END_SIM_TIME_ROOTAGE
  
}

write.table(ROOT_TIME_MAT,"LOTRT0.5_KeyRootAgeTimes.out", sep = " ")

```

```{r}
for (s in 1:dim(SEED_LIST_ALL)[1]) {
  SEEDVAL = as.character(SEED_LIST_ALL[s,1])
  message(SEEDVAL)
  INFILENAME = paste("MESA_X5Balance_test_s",SEEDVAL,"_hitrtext0.5_NEW.out",sep="")
  
  DATA = read.table(INFILENAME,header=T)
  
  PRE_EXT_TIME_ROW = which(DATA[,1]==PRE_EXT_TIME)
  PRE_EXT_TIME_RTDIST = DATA[PRE_EXT_TIME_ROW,12]
  PRE_EXT_TIME_ROOTAGE = PRE_EXT_TIME - PRE_EXT_TIME_RTDIST
  
  POST_EVENT_TIME_ROW = which(DATA[,1]==POST_EVENT_TIME)
  POST_EVENT_TIME_RTDIST = DATA[POST_EVENT_TIME_ROW,12]
  POST_EVENT_TIME_ROOTAGE = POST_EVENT_TIME - POST_EVENT_TIME_RTDIST
  
  HITRT_CSR_TIME = HITRT_0.5_CSRTIMES[s]
  
  RCT_TIME_ROW = which(DATA[,1]==HITRT_CSR_TIME)
  RCT_TIME_RTDIST = DATA[RCT_TIME_ROW,12]
  RCT_TIME_ROOTAGE = HITRT_CSR_TIME - RCT_TIME_RTDIST
  
  PEAK_IMBAL_VAL = max(DATA[,6])#max val coll_blum
  PEAK_IMBAL_ROW = which(DATA[,6]==PEAK_IMBAL_VAL)
  PEAK_IMBAL_TIME = DATA[PEAK_IMBAL_ROW,1]
  PEAK_IMBAL_RTDIST = DATA[PEAK_IMBAL_ROW,12]
  PEAK_IMBAL_ROOTAGE = PEAK_IMBAL_TIME - PEAK_IMBAL_RTDIST
  
  CSR_END_MID_TIME = ((END_SIM_TIME - RAND_CSR_TIME)%/%2) + RAND_CSR_TIME
  if ((CSR_END_MID_TIME %% 5) > 0) CSR_END_MID_TIME = CSR_END_MID_TIME + 3 
  
  CSR_END_MID_TIME_ROW = which(DATA[,1]==CSR_END_MID_TIME)
  CSR_END_MID_TIME_RTDIST = DATA[CSR_END_MID_TIME_ROW,12]
  CSR_END_MID_ROOTAGE = CSR_END_MID_TIME - CSR_END_MID_TIME_RTDIST
  
  END_SIM_TIME_ROW = which(DATA[,1]==END_SIM_TIME)
  END_SIM_TIME_RTDIST = DATA[END_SIM_TIME_ROW,12]
  END_SIM_TIME_ROOTAGE = END_SIM_TIME - END_SIM_TIME_RTDIST
  
  ROOT_TIME_MAT[s,2] = PRE_EXT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,3] = POST_EVENT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,4] = RCT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,5] = PEAK_IMBAL_ROOTAGE
  ROOT_TIME_MAT[s,6] = CSR_END_MID_ROOTAGE
  ROOT_TIME_MAT[s,7] = END_SIM_TIME_ROOTAGE
  
}

write.table(ROOT_TIME_MAT,"HITRT0.5_KeyRootAgeTimes.out", sep = " ")

```

```{r}
RAND_0.75_CSRTIMES = CSR_TIMES[,5]
HITRT_0.75_CSRTIMES = CSR_TIMES[,6]
LOTRT_0.75_CSRTIMES = CSR_TIMES[,7]

for (s in 1:dim(SEED_LIST_ALL)[1]) {
  SEEDVAL = as.character(SEED_LIST_ALL[s,1])
  message(SEEDVAL)
  INFILENAME = paste("MESA_X5Balance_test_s",SEEDVAL,"_randext0.75_NEW.out",sep="")
  
  DATA = read.table(INFILENAME,header=T)
  
  PRE_EXT_TIME_ROW = which(DATA[,1]==PRE_EXT_TIME)
  PRE_EXT_TIME_RTDIST = DATA[PRE_EXT_TIME_ROW,12]
  PRE_EXT_TIME_ROOTAGE = PRE_EXT_TIME - PRE_EXT_TIME_RTDIST
  
  POST_EVENT_TIME_ROW = which(DATA[,1]==POST_EVENT_TIME)
  POST_EVENT_TIME_RTDIST = DATA[POST_EVENT_TIME_ROW,12]
  POST_EVENT_TIME_ROOTAGE = POST_EVENT_TIME - POST_EVENT_TIME_RTDIST
  
  RAND_CSR_TIME = RAND_0.75_CSRTIMES[s]
  
  RCT_TIME_ROW = which(DATA[,1]==RAND_CSR_TIME)
  RCT_TIME_RTDIST = DATA[RCT_TIME_ROW,12]
  RCT_TIME_ROOTAGE = RAND_CSR_TIME - RCT_TIME_RTDIST
  
  PEAK_IMBAL_VAL = max(DATA[,6])
  PEAK_IMBAL_ROW = which(DATA[,6]==PEAK_IMBAL_VAL)
  PEAK_IMBAL_TIME = DATA[PEAK_IMBAL_ROW,1]
  PEAK_IMBAL_RTDIST = DATA[PEAK_IMBAL_ROW,12]
  PEAK_IMBAL_ROOTAGE = PEAK_IMBAL_TIME - PEAK_IMBAL_RTDIST
  
  CSR_END_MID_TIME = ((END_SIM_TIME - RAND_CSR_TIME)%/%2) + RAND_CSR_TIME
  if ((CSR_END_MID_TIME %% 5) > 0) CSR_END_MID_TIME = CSR_END_MID_TIME + 3 
  
  CSR_END_MID_TIME_ROW = which(DATA[,1]==CSR_END_MID_TIME)
  CSR_END_MID_TIME_RTDIST = DATA[CSR_END_MID_TIME_ROW,12]
  CSR_END_MID_ROOTAGE = CSR_END_MID_TIME - CSR_END_MID_TIME_RTDIST
  
  END_SIM_TIME_ROW = which(DATA[,1]==END_SIM_TIME)
  END_SIM_TIME_RTDIST = DATA[END_SIM_TIME_ROW,12]
  END_SIM_TIME_ROOTAGE = END_SIM_TIME - END_SIM_TIME_RTDIST
  
  ROOT_TIME_MAT[s,2] = PRE_EXT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,3] = POST_EVENT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,4] = RCT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,5] = PEAK_IMBAL_ROOTAGE
  ROOT_TIME_MAT[s,6] = CSR_END_MID_ROOTAGE
  ROOT_TIME_MAT[s,7] = END_SIM_TIME_ROOTAGE
  
}

write.table(ROOT_TIME_MAT,"RAND0.75_KeyRootAgeTimes.out", sep = " ")

```

```{r}
for (s in 1:dim(SEED_LIST_ALL)[1]) {
  SEEDVAL = as.character(SEED_LIST_ALL[s,1])
  message(SEEDVAL)
  INFILENAME = paste("MESA_X5Balance_test_s",SEEDVAL,"_lotrtext0.75_NEW.out",sep="")
  
  DATA = read.table(INFILENAME,header=T)
  
  PRE_EXT_TIME_ROW = which(DATA[,1]==PRE_EXT_TIME)
  PRE_EXT_TIME_RTDIST = DATA[PRE_EXT_TIME_ROW,12]
  PRE_EXT_TIME_ROOTAGE = PRE_EXT_TIME - PRE_EXT_TIME_RTDIST
  
  POST_EVENT_TIME_ROW = which(DATA[,1]==POST_EVENT_TIME)
  POST_EVENT_TIME_RTDIST = DATA[POST_EVENT_TIME_ROW,12]
  POST_EVENT_TIME_ROOTAGE = POST_EVENT_TIME - POST_EVENT_TIME_RTDIST
  
  LOTRT_CSR_TIME = LOTRT_0.75_CSRTIMES[s]
  
  RCT_TIME_ROW = which(DATA[,1]==LOTRT_CSR_TIME)
  RCT_TIME_RTDIST = DATA[RCT_TIME_ROW,12]
  RCT_TIME_ROOTAGE = LOTRT_CSR_TIME - RCT_TIME_RTDIST
  
  PEAK_IMBAL_VAL = max(DATA[,6])
  PEAK_IMBAL_ROW = which(DATA[,6]==PEAK_IMBAL_VAL)
  PEAK_IMBAL_TIME = DATA[PEAK_IMBAL_ROW,1]
  PEAK_IMBAL_RTDIST = DATA[PEAK_IMBAL_ROW,12]
  PEAK_IMBAL_ROOTAGE = PEAK_IMBAL_TIME - PEAK_IMBAL_RTDIST
  
  CSR_END_MID_TIME = ((END_SIM_TIME - RAND_CSR_TIME)%/%2) + RAND_CSR_TIME
  if ((CSR_END_MID_TIME %% 5) > 0) CSR_END_MID_TIME = CSR_END_MID_TIME + 3 
  
  CSR_END_MID_TIME_ROW = which(DATA[,1]==CSR_END_MID_TIME)
  CSR_END_MID_TIME_RTDIST = DATA[CSR_END_MID_TIME_ROW,12]
  CSR_END_MID_ROOTAGE = CSR_END_MID_TIME - CSR_END_MID_TIME_RTDIST
  
  END_SIM_TIME_ROW = which(DATA[,1]==END_SIM_TIME)
  END_SIM_TIME_RTDIST = DATA[END_SIM_TIME_ROW,12]
  END_SIM_TIME_ROOTAGE = END_SIM_TIME - END_SIM_TIME_RTDIST
  
  ROOT_TIME_MAT[s,2] = PRE_EXT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,3] = POST_EVENT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,4] = RCT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,5] = PEAK_IMBAL_ROOTAGE
  ROOT_TIME_MAT[s,6] = CSR_END_MID_ROOTAGE
  ROOT_TIME_MAT[s,7] = END_SIM_TIME_ROOTAGE
  
}

write.table(ROOT_TIME_MAT,"LOTRT0.75_KeyRootAgeTimes.out", sep = " ")
```

```{r}
for (s in 1:dim(SEED_LIST_ALL)[1]) {
  SEEDVAL = as.character(SEED_LIST_ALL[s,1])
  message(SEEDVAL)
  INFILENAME = paste("MESA_X5Balance_test_s",SEEDVAL,"_hitrtext0.75_NEW.out",sep="")
  
  DATA = read.table(INFILENAME,header=T)
  
  PRE_EXT_TIME_ROW = which(DATA[,1]==PRE_EXT_TIME)
  PRE_EXT_TIME_RTDIST = DATA[PRE_EXT_TIME_ROW,12]
  PRE_EXT_TIME_ROOTAGE = PRE_EXT_TIME - PRE_EXT_TIME_RTDIST
  
  POST_EVENT_TIME_ROW = which(DATA[,1]==POST_EVENT_TIME)
  POST_EVENT_TIME_RTDIST = DATA[POST_EVENT_TIME_ROW,12]
  POST_EVENT_TIME_ROOTAGE = POST_EVENT_TIME - POST_EVENT_TIME_RTDIST
  
  HITRT_CSR_TIME = HITRT_0.75_CSRTIMES[s]
  
  RCT_TIME_ROW = which(DATA[,1]==HITRT_CSR_TIME)
  RCT_TIME_RTDIST = DATA[RCT_TIME_ROW,12]
  RCT_TIME_ROOTAGE = HITRT_CSR_TIME - RCT_TIME_RTDIST
  
  PEAK_IMBAL_VAL = max(DATA[,6])
  PEAK_IMBAL_ROW = which(DATA[,6]==PEAK_IMBAL_VAL)
  PEAK_IMBAL_TIME = DATA[PEAK_IMBAL_ROW,1]
  PEAK_IMBAL_RTDIST = DATA[PEAK_IMBAL_ROW,12]
  PEAK_IMBAL_ROOTAGE = PEAK_IMBAL_TIME - PEAK_IMBAL_RTDIST
  
  CSR_END_MID_TIME = ((END_SIM_TIME - RAND_CSR_TIME)%/%2) + RAND_CSR_TIME
  if ((CSR_END_MID_TIME %% 5) > 0) CSR_END_MID_TIME = CSR_END_MID_TIME + 3 
  
  CSR_END_MID_TIME_ROW = which(DATA[,1]==CSR_END_MID_TIME)
  CSR_END_MID_TIME_RTDIST = DATA[CSR_END_MID_TIME_ROW,12]
  CSR_END_MID_ROOTAGE = CSR_END_MID_TIME - CSR_END_MID_TIME_RTDIST
  
  END_SIM_TIME_ROW = which(DATA[,1]==END_SIM_TIME)
  END_SIM_TIME_RTDIST = DATA[END_SIM_TIME_ROW,12]
  END_SIM_TIME_ROOTAGE = END_SIM_TIME - END_SIM_TIME_RTDIST
  
  ROOT_TIME_MAT[s,2] = PRE_EXT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,3] = POST_EVENT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,4] = RCT_TIME_ROOTAGE
  ROOT_TIME_MAT[s,5] = PEAK_IMBAL_ROOTAGE
  ROOT_TIME_MAT[s,6] = CSR_END_MID_ROOTAGE
  ROOT_TIME_MAT[s,7] = END_SIM_TIME_ROOTAGE
  
}

write.table(ROOT_TIME_MAT,"HITRT0.75_KeyRootAgeTimes.out", sep = " ")

```

